fallback-grpc-addr: 127.0.0.1:9966
fallback-http-addr: 127.0.0.1:9967
dial-grpc-timeout: 10s

order:
  service-name: order
  server-to-run: http
  http-addr: 127.0.0.1:8082
  grpc-addr: 127.0.0.1:5002
  metrics-export-addr: 0.0.0.0:9091

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 127.0.0.1:8083
  grpc-addr: 127.0.0.1:5003
  metrics-export-addr: 0.0.0.0:9092

payment:
  service-name: payment
  server-to-run: http
  http-addr: 127.0.0.1:8084
  grpc-addr: 127.0.0.1:5004
  metrics-export-addr: 0.0.0.0:9093

kitchen:
  service-name: kitchen

consul:
  addr: 127.0.0.1:8500

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 5672
  max-retry: 3

mongo:
  user: root
  password: password
  host: 127.0.0.1
  port: 27017

  db-name: "order"
  coll-name: "order"

jaeger:
  url: "http://127.0.0.1:14268/api/traces"

mysql:
    user: root
    password: root
    host: 127.0.0.1
    port: 3307
    database: gorder

redis:
  local:
    ip: 127.0.0.1
    port: 6379
    pool_size: 100
    max_coon: 100
    conn_timeout: 1000
    read_timeout: 1000
    write_timeout: 100

stripe-key: ${STRIPE_KEY}
endpoint-stripe-secret: ${ENDPOINT_STRIPE_SECRET}