fallback-grpc-addr: 127.0.0.1:9966
fallback-http-addr: 127.0.0.1:9967

order:
  service-name: order
  server-to-run: http
  http-addr: 127.0.0.1:8082
  grpc-addr: 127.0.0.1:5002

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 127.0.0.1:8083
  grpc-addr: 127.0.0.1:5003

payment:
  service-name: payment
  server-to-run: http
  http-addr: 127.0.0.1:8084
  grpc-addr: 127.0.0.1:5004

consul:
  addr: 127.0.0.1:8500
stripe-key: ${STRIPE_KEY}