fallback-grpc-addr: 127.0.0.1:9966
fallback-http-addr: 127.0.0.1:9967
dial-grpc-timeout: 10s

order:
  service-name: order
  server-to-run: http
  http-addr: 127.0.0.1:8082
  grpc-addr: 127.0.0.1:5002

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 127.0.0.1:8083
  grpc-addr: 127.0.0.1:5003

payment:
  service-name: payment
  server-to-run: http
  http-addr: 127.0.0.1:8084
  grpc-addr: 127.0.0.1:5004

consul:
  addr: 127.0.0.1:8500

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 5672
  max-retry: 3

jaeger:
  url: "http://127.0.0.1:14268/api/traces"

stripe-key: ${STRIPE_KEY}
endpoint-stripe-secret: ${ENDPOINT_STRIPE_SECRET}